const {test,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const os=require('os');
const path=require('path');
const ExcelJS=require('exceljs');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rrhh-test-'));
process.env.DATA_DIR=dir;
const {app,db}=require('../server');
const server=app.listen(0,'127.0.0.1');
let cookie='';
async function request(route,method='GET',body,auth=true){const response=await fetch(`http://127.0.0.1:${server.address().port}/api${route}`,{method,headers:{...(body instanceof FormData?{}:{'Content-Type':'application/json'}),...(auth?{Cookie:cookie}:{})},body:body instanceof FormData?body:body?JSON.stringify(body):undefined});return {status:response.status,body:await response.json(),headers:response.headers};}
test('Acceso, fichas concurrentes, importación, convocatorias y permisos',async()=>{
 assert.equal((await request('/candidates')).status,401);
 for(const route of ['/whatsapp','/sync','/files/unknown','/exports/unknown/download'])assert.equal((await request(route)).status,401);
 assert.equal((await request('/setup','POST',{username:'admin',password:'correcta-prueba-123',token:'incorrecto'})).status,403);
 assert.equal((await request('/setup','POST',{username:'admin',password:'correcta-prueba-123',token:fs.readFileSync(path.join(dir,'clave-inicial.txt'),'utf8')})).status,200);
 const login=await request('/login','POST',{username:'admin',password:'correcta-prueba-123'});cookie=login.headers.get('set-cookie').split(';')[0];
 const created=await request('/candidates','POST',{name:'Persona de prueba',phone:'1112345678',license:'C1',distance:10});assert.equal(created.status,200);
 const id=created.body.id;let row=(await request('/candidates')).body[0];assert.equal(row.name,'Persona de prueba');
 assert.equal((await request('/candidates/'+id,'PUT',{...row,status:'Revisado'})).status,200);
 assert.equal((await request('/candidates/'+id,'PUT',{...row,status:'Archivado'})).status,409);
 const campaign=await request('/campaigns','POST',{title:'Entrevistas de prueba',date:'2026-09-16',time:'09:00',capacity:1});const cid=campaign.body.id;
 assert.equal((await request(`/campaigns/${cid}/invitations`,'POST',{ids:[id]})).status,200);
 const second=(await request('/candidates','POST',{name:'Otra persona'})).body.id;
 assert.equal((await request(`/campaigns/${cid}/invitations`,'POST',{ids:[second]})).status,400);
 assert.equal((await request(`/campaigns/${cid}/invitations/${id}`,'PUT',{status:'Confirmó'})).status,200);
 assert.equal((await request('/campaigns')).body[0].invitations[0].status,'Confirmó');
 const book=new ExcelJS.Workbook();book.addWorksheet('Postulantes').addRows([['Nombre y apellido','WhatsApp','Localidad','Licencia'],['Importado','1122223333','Virrey del Pino','B1']]);const form=new FormData();form.append('file',new Blob([await book.xlsx.writeBuffer()]),'prueba.xlsx');
 const preview=await request('/import/preview','POST',form);assert.equal(preview.body.rows[0].name,'Importado');
 assert.equal((await request('/import/commit','POST',{rows:preview.body.rows})).body.added,1);
 assert.equal((await request('/import/commit','POST',{rows:preview.body.rows})).body.skipped,1);
 const rollback=await request('/import/commit','POST',{rows:[{name:'No debe guardarse'},{name:''}]});assert.equal(rollback.status,400);assert.equal((await request('/candidates')).body.length,3);
 const invalid=new FormData();invalid.append('file',new Blob(['executable']),'programa.exe');assert.equal((await request(`/candidates/${id}/documents`,'POST',invalid)).status,400);
 assert.equal((await request('/users','POST',{username:'operador',password:'otra-clave-prueba-123'})).status,200);
 const login2=await request('/login','POST',{username:'operador',password:'otra-clave-prueba-123'});cookie=login2.headers.get('set-cookie').split(';')[0];
 assert.equal((await request('/users','POST',{username:'tercero',password:'otra-clave-prueba-123'})).status,403);
 assert.equal((await request('/backup','POST')).status,403);
 assert.equal((await request('/whatsapp/connect','POST',{exclusiveAccount:true})).status,403);
 assert.equal((await request('/sync','POST',{start:'2026-09-09',end:'2026-09-10'})).status,403);
 assert.equal((await request('/whatsapp')).body.qr,null);
 await request('/logout','POST');assert.equal((await request('/candidates')).status,401);
});
after(async()=>{await new Promise(resolve=>server.close(resolve));db.close();fs.rmSync(dir,{recursive:true,force:true});});
